<?xml version="1.0" encoding="utf-8"?><Database Name="Baza" Class="BazaDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=(LocalDB)\MSSQLLocalDB;AttachDbFilename=|DataDirectory|\Baza.mdf;Integrated Security=True;Connect Timeout=30" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="BazaConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Danie" Member="Danies">
    <Type Name="Danie">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="nazwa" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="kategoria" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="przepis" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Association Name="Danie_Skladnik" Member="Skladniks" ThisKey="Id" OtherKey="Id_dania" Type="Skladnik" />
      <Association Name="Danie_Dania_Menu" Member="Dania_Menus" ThisKey="Id" OtherKey="Id_dania" Type="Dania_Menu" />
    </Type>
  </Table>
  <Table Name="dbo.Produkt_spozywczy" Member="Produkt_spozywczies">
    <Type Name="Produkt_spozywczy">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="nazwa" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="jednostka" Type="System.String" DbType="NVarChar(4) NOT NULL" CanBeNull="false" />
      <Column Name="kalorie" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="weglowodany" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="bialka" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="blonnik" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="sol" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="tluszcze" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Association Name="Produkt_spozywczy_Skladnik" Member="Skladniks" ThisKey="Id" OtherKey="Id_produktu" Type="Skladnik" />
    </Type>
  </Table>
  <Table Name="dbo.Skladnik" Member="Skladniks">
    <Type Name="Skladnik">
      <Column Name="Id_dania" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Id_produktu" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ilosc" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Danie_Skladnik" Member="Danie" ThisKey="Id_dania" OtherKey="Id" Type="Danie" IsForeignKey="true" />
      <Association Name="Produkt_spozywczy_Skladnik" Member="Produkt_spozywczy" ThisKey="Id_produktu" OtherKey="Id" Type="Produkt_spozywczy" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Dania_Menu" Member="Dania_Menus">
    <Type Name="Dania_Menu">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Id_menu" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Id_dania" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Danie_Dania_Menu" Member="Danie" ThisKey="Id_dania" OtherKey="Id" Type="Danie" IsForeignKey="true" />
      <Association Name="Menu_Dania_Menu" Member="Menu" ThisKey="Id_menu" OtherKey="id" Type="Menu" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Menu" Member="Menus">
    <Type Name="Menu">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="data" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="id_klienta" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="id_dietetyka" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Menu_Dania_Menu" Member="Dania_Menus" ThisKey="id" OtherKey="Id_menu" Type="Dania_Menu" />
      <Association Name="Konto_Menu" Member="Konto" ThisKey="id_dietetyka" OtherKey="Id" Type="Konto" IsForeignKey="true" />
      <Association Name="Konto_Menu1" Member="Konto1" ThisKey="id_klienta" OtherKey="Id" Type="Konto" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Konto" Member="Kontos">
    <Type Name="Konto">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="imie" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="nazwisko" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="rodzaj" Type="System.Char" DbType="Char(1) NOT NULL" CanBeNull="false" />
      <Column Name="login" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="haslo" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="telefon" Type="System.String" DbType="NChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="plan_kalorii" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Konto_Menu" Member="Menus" ThisKey="Id" OtherKey="id_dietetyka" Type="Menu" />
      <Association Name="Konto_Menu1" Member="Menus1" ThisKey="Id" OtherKey="id_klienta" Type="Menu" />
      <Association Name="Konto_Plan_zywienia" Member="Plan_zywienias" ThisKey="Id" OtherKey="Id_konta" Type="Plan_zywienia" />
    </Type>
  </Table>
  <Table Name="dbo.Plan_zywienia" Member="Plan_zywienias">
    <Type Name="Plan_zywienia">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="kalorie" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="weglowodany" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="bialka" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="blonnik" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="sol" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="tluszcze" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Id_konta" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Konto_Plan_zywienia" Member="Konto" ThisKey="Id_konta" OtherKey="Id" Type="Konto" IsForeignKey="true" />
    </Type>
  </Table>
</Database>